ci: Enable clang build again
Since gnomeos updated to the newer malcontent, clang
was rightfully complaining about the type missmatch.

```
../gnome-initial-setup/pages/parental-controls/gis-parental-controls-page.c:160:44: error: implicit conversion from enumeration type 'ActUserAccountType' to different enumeration type 'MctUserType' [-Werror,-Wimplicit-enum-enum-cast]
159 |   mct_user_controls_set_user_account_type (MCT_USER_CONTROLS (page->user_controls),
    |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
160 |                                            ACT_USER_ACCOUNT_TYPE_STANDARD);
    |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Now that the last commit fixed that, enable the build again

Part-of: <https://gitlab.gnome.org/GNOME/gnome-initial-setup/-/merge_requests/304>